INSERT INTO BANK (name, address, paysystem) values ('Ultra Strong Bank', 'Chicago, Unter den Linden, 14', 'VISA, MASTERCARD, JCB, UNION, MAESTRO');
INSERT INTO BANK (name, address, paysystem) values ('Ultra Solid Repository', 'Berlin, Achilles st, 14', 'VISA, MASTERCARD, JCB, UNION, MAESTRO');
INSERT INTO BANK (name, address, paysystem) values ('Extra Safe Repository', 'Moscow, Achilles st, 64', 'VISA, MASTERCARD, JCB, UNION, MAESTRO');
INSERT INTO BANK (name, address, paysystem) values ('Stone Reliable Repository', 'Chicago, Unter den Linden, 14', 'VISA, MASTERCARD, JCB, UNION, MAESTRO');
INSERT INTO BANK (name, address, paysystem) values ('Mega Safe Repository', 'Moscow, Unter den Linden, 20', 'VISA, MASTERCARD, JCB, UNION, MAESTRO');
INSERT INTO BANK (name, address, paysystem) values ('Mega Secure Bank Solutions', 'Moscow, Downing st, 64', 'VISA, MASTERCARD, JCB, UNION, MAESTRO');
INSERT INTO BANK (name, address, paysystem) values ('Stone Safe Repository', 'Moscow, Unter den Linden, 20', 'VISA, MASTERCARD, JCB, UNION, MAESTRO');
INSERT INTO BANK (name, address, paysystem) values ('Mega Solid Bank', 'London, Lenin st, 38', 'VISA, MASTERCARD, JCB, UNION, MAESTRO');
INSERT INTO BANK (name, address, paysystem) values ('Mega Secure Bank Solutions', 'Berlin, Downing st, 20', 'VISA, MASTERCARD, JCB, UNION, MAESTRO');
INSERT INTO BANK (name, address, paysystem) values ('Extra Solid Bank', 'Moscow, Achilles st, 20', 'VISA, MASTERCARD, JCB, UNION, MAESTRO');
INSERT INTO BANK (name, address, paysystem) values ('Super Secure Bank', 'Berlin, Unter den Linden, 14', 'VISA, MASTERCARD, JCB, UNION, MAESTRO');
INSERT INTO BANK (name, address, paysystem) values ('Ultra Reliable Bank', 'Chicago, Downing st, 14', 'VISA, MASTERCARD, JCB, UNION, MAESTRO');
INSERT INTO BANK (name, address, paysystem) values ('Super Strong Bank Solutions', 'Chicago, Lenin st, 38', 'VISA, MASTERCARD, JCB, UNION, MAESTRO');
INSERT INTO BANK (name, address, paysystem) values ('Mega Old Bank Solutions', 'London, Lenin st, 38', 'VISA, MASTERCARD, JCB, UNION, MAESTRO');
INSERT INTO BANK (name, address, paysystem) values ('Mega Strong Repository', 'Berlin, Downing st, 64', 'VISA, MASTERCARD, JCB, UNION, MAESTRO');
INSERT INTO BANK (name, address, paysystem) values ('Extra Secure Bank', 'Berlin, Unter den Linden, 14', 'VISA, MASTERCARD, JCB, UNION, MAESTRO');
INSERT INTO BANK (name, address, paysystem) values ('Mega Secure Bank Solutions', 'Berlin, Achilles st, 20', 'VISA, MASTERCARD, JCB, UNION, MAESTRO');
INSERT INTO BANK (name, address, paysystem) values ('Mega Reliable Repository', 'Berlin, Lenin st, 64', 'VISA, MASTERCARD, JCB, UNION, MAESTRO');
INSERT INTO BANK (name, address, paysystem) values ('Stone Secure Bank Solutions', 'Chicago, Downing st, 38', 'VISA, MASTERCARD, JCB, UNION, MAESTRO');
INSERT INTO BANK (name, address, paysystem) values ('Stone Secure Bank Solutions', 'Chicago, Lenin st, 64', 'VISA, MASTERCARD, JCB, UNION, MAESTRO');
